# Change these first
owner: diggajupadhyay # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Diggaj Upadhyay
    url: https://diggajupadhyay.com.np
    maxResponseTime: 5000
  - name: Ayush Bhandari
    url: http://ayushbhandari.com.np/
    assignees:
      - AyushBhandari
    maxResponseTime: 5000
  - name: Nischal Pantha
    url: http://bpantha.com.np/
    assignees:
      - NischalPantha
    maxResponseTime: 5000
  - name: LKC Visuals
    url: http://lkcvisuals.com/
    assignees:
      - LKCVisuals
    maxResponseTime: 5000


status-website:
  # design
  theme: dark
  logoUrl: https://diggajupadhyay.com.np/logo.png

  # custom location
  baseUrl: /upptime
  name: This is how we roll

  # nav-bar
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  
  # body
  introTitle: "**Upptime** is the open-source uptime monitor and status page,
  powered entirely by GitHub."
  introMessage: "**Welcome** ease back and feel comfortable to go through every
  option to get the best out of this."

  # fav icon
  favicon: https://diggajupadhyay.com.np/logo.png

  # Custom robots.txt files
  robotsText: "User-agent: * \n Disallow: /"